POST http://localhost:8080/api/payments
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "value": "1 PLN"
}

###

GET http://localhost:8080/api/payments/bc8730dd-1dd6-4d9d-9809-04e7f7629577
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/api/payments/started?pageSize=10
Accept: application/json
Content-Type: application/json
#Authorization: Basic YWRtaW46YWRtaW4=
Authorization: Basic YWRtaW5AdHJhaW5pbmcucGw6YWRtaW4=

###

GET http://localhost:8080/api/users/me
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW5AdHJhaW5pbmcucGw6YWRtaW4=
